server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.41.57.98:3306/RENT_SYS?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: shijiu

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sgfb.rent.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  configuration:
    jdbc-type-for-null: NULL

logging:
  level:
    com.sgfb.rent: debug
